version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
      - image: circleci/openjdk:9.0.4-jdk-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.141.59.jar -log test-reports/selenium.log
          background: true
      - run: mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
          when: always
      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber
