orbs:
  maven: circleci/maven@1.2.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
      - run:
          name: Check Details
          command: |
            pwd
            cd target
            ls
          
